app01/urls.py
from django.urls import path
from . import views
app_name = 'app01'
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    # path("user/list/", views.user_list, name="list"),
    path("user/add/", views.user_add, name="user_add"),
    # path("user/<int:id_>/delete/", views.user_delete, name="user_delete"),
    # path("user/<int:id_>/edit/", views.user_edit, name="user_edit"),
]

item/urls.py
# from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    # path('admin/', admin.site.urls),
    path("app01/", include("app01.urls")),
    path("ys/", include("ys.urls")),
    path("play/", include("play.urls")),
]

play/urls.py
from django.urls import path
from . import views
app_name = 'play'
urlpatterns = [
    path("index/", views.index, name="index"),
    path("article/<int:id_>/", views.article, name="article"),
    path("main/", views.main, name="main"),
    path("api/", views.api, name="api"),
    ]

ys/urls.py
from django.urls import path
from . import views
app_name = 'ys'
urlpatterns = [
    path("home/", views.home, name="home"),
    path("user/<int:id_>/", views.user, name="user"),
    path("article/<int:id_>/", views.article, name="article"),
    path("delete/<int:id_>/article", views.delete_article, name="delete_article"),
    path("create/topic/", views.create_topic, name="create_topic"),
    path("write/", views.write, name="write"),
    path("edit/<int:id_>/", views.edit, name="edit"),
    path("like/article/<int:id_>/", views.like_article, name="like_article"),
    path("favorite/article/<int:id_>/", views.favorite_article, name="favorite_article"),

]

play/models.py
from django.db import models

# Create your models here.

play/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from ys import models
from django.db.models import Q
import json
import akshare as ak
import pandas as pd
# Create your views here.


def index(request):
    search = request.GET.get('search')
    if search:
        posts = models.Post.objects.filter(
            Q(title__contains=search) | Q(author__name__contains=search) | Q(content__contains=search))
    else:
        posts = models.Post.objects.all()
    return render(request, 'index.html', {'posts': posts})

def article(request, id_):
    post = models.Post.objects.filter(id=id_)
    if not post:
        return HttpResponse('文章不存在')
    post = post.first()
    comments = models.Comment.objects.filter(post=post)
    like_nums = models.Like.objects.filter(post=post).count()
    favorite_nums = models.Favorite.objects.filter(post=post).count()
    form = {
        'post': post,
        'comments': comments,
        'flag': False,
        'like_nums': like_nums,
        'favorite_nums': favorite_nums,
    }
    # print(post.author.id, request.session['info']['id'])
    if request.session.get('info') and post.author.id == request.session['info']['id']:
        form['flag'] = True
    return render(request, 'open_article.html', form)

def main(request):
    form = {}
    return render(request, 'main.html',form)

def api(request):
    if request.method == 'POST':
        data0 = json.loads(request.body.decode('utf-8'))
        input_data = data0.get('input_data')
        '''
        "stock_info_sz_name_code"  # 深证证券交易所股票代码和简称
         "stock_info_sh_name_code"  # 上海证券交易所股票代码和简称
         "stock_info_bj_name_code"  # 北京证券交易所股票代码和简称'''
        # print(input_data)
        data, first, new_data = profitability(input_data)
        data2, first2 = solvency(input_data)
        data3, first3 = money(input_data)
        # 加权净资产收益率（加权ROE =归属于母公司所有者的净利润 / 归属于母公司股东权益合计# 归属于母公司所有者的净利润 资产负债表：归属于母公司股东权益合计
        p1 = first['归属于母公司所有者的净利润'][0] / first2['归属于母公司股东权益合计'][0] * 100
        # 净利润同比增速
        p2 = (first['净利润'][0] - first['净利润'][4]) / first['净利润'][4] * 100
        # 总资产周转率
        p3 = first['营业收入'][0] / (first2['资产总计'][0] + first2['资产总计'][1]) * 2 * 100
        # 销售现金比率
        p4 = first3['销售商品、提供劳务收到的现金'][0] / first['营业收入'][0] * 100
        # 资产负债率
        p5 = first2['负债合计'][0] / first2['资产总计'][0] * 100
        # pie = [[first['净利润'][i],first['报告日'][i]]  for i in range(1, 5)]
        pie = [{'value': first['营业收入'][i], 'name': str(first['报告日'][i])[:10]} for i in range(1, 5)]
        # print(pie)
        form = {
            'data1':data,
            'data2':data2,
            'leida': [round(p1, 2), round(p2, 2), round(p3, 2), round(p4, 2), round(p5, 2), ],
            'pie': pie,
            'new_data':new_data,
        }
        return JsonResponse(form)

# 盈利能力
def profitability(stock):
    df = ak.stock_financial_report_sina(stock=stock, symbol="利润表")
    # df.to_excel("利润表.xlsx")
    df['报告日'] = pd.to_datetime(df['报告日'])
    # 提取年份
    df['年份'] = df['报告日'].dt.year
    first = df.head(6).to_dict(orient='list')
    new_data = df[df['报告日'].dt.year > 2019][['报告日', '营业收入', '营业成本']].reset_index()
    new_data['报告日'] =  new_data['报告日'].astype(str).str[:10]
    new_data['营业收入'] = new_data['营业收入'] / 100000000
    new_data['营业成本'] = new_data['营业成本'] / 100000000
    new_data = new_data.sort_values(by='报告日')
    new_data = new_data.to_dict(orient='list')
    # to_dict(orient='list'))
    # 按年份汇总
    df = df.groupby('年份')[['营业收入', '营业成本', '营业利润', '净利润']].sum().reset_index()
    df = df[(df['年份'] > 2019) & (df['年份'] < 2025)]
    df['毛利率'] = (df['营业收入'] - df['营业成本']) / df['营业收入']*100
    df['营业利润率'] = df['营业利润'] / df['营业收入']*100
    df['净利率'] = df['净利润'] / df['营业收入']*100
    dict_data = df.to_dict(orient='list')
    # df.to_excel("盈利能力.xlsx")
    return dict_data, first, new_data

# 短期偿债能力
def solvency(stock):
    df = ak.stock_financial_report_sina(stock=stock, symbol="资产负债表")
    # df.to_excel("资产负债表.xlsx")
    df['报告日'] = pd.to_datetime(df['报告日'])
    # 提取年份
    df['年份'] = df['报告日'].dt.year
    first = df.head(6).to_dict(orient='list')
    # 按年份汇总
    df = df.groupby('年份')[['流动资产合计', '流动负债合计', '存货', '预付款项', '负债合计', '资产总计']].sum().reset_index()
    df = df[(df['年份'] > 2019) & (df['年份'] < 2025)]
    df['流动比率'] = df['流动资产合计'] / df['流动负债合计']
    df['速动比率'] = (df['流动资产合计'] - df['存货'] - df['预付款项']) / df['流动负债合计']
    df['资产负债率'] = df['负债合计'] / df['资产总计']*100
    dict_data = df.to_dict(orient='list')
    # print(dict_data)
    # df.to_excel("短期偿债能力.xlsx")
    return dict_data, first

def money(stock):
    df = ak.stock_financial_report_sina(stock=stock, symbol="现金流量表")
    df['报告日'] = pd.to_datetime(df['报告日'])
    # 提取年份
    df['年份'] = df['报告日'].dt.year
    first = df.head(6).to_dict(orient='list')
    df = df[(df['年份'] > 2019) & (df['年份'] < 2025)]
    dict_data = df.to_dict(orient='list')
    return dict_data, first

play/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
</head>
<body>
    <div class="navbar">
        <a href="{% url 'play:index' %}">首页</a>
{#        <a href="{% url 'ys:user' id_=user.id %}">我的主页</a>#}
        <a href="{% url 'ys:create_topic' %}" target="_blank">新建话题</a>
        <a href="{% url 'ys:write' %}" target="_blank">写文章</a>
	<a href="http://120.79.36.136:3000/" target="_blank">Open WebUI</a>
	<a href="{% url 'play:main' %}"  target="_blank">财务报表可视化</a>
        <div class="search-container">
            <form action="{% url 'ys:home' %}" method="get">
                <label>
              <input type="text" placeholder="搜索" value="" class="input1" name="search">
                    </label>
              <button class="button1" type="submit">搜索</button>
            </form>
        </div>
        <a href="{% url 'app01:login' %}">请登录</a>
        <a href="{% url 'app01:logout' %}">退出登录</a>
    </div>
    <div class="container">
        <h1 style="text-align: center">所有帖子</h1>
    {% for post in posts %}
        <div class="article-card">
            <div class="article-card-user-info">
                <a href="{% url 'ys:user' id_=post.author.id %}" class="link-styled"><span style="padding: 10px;">{{ post.author }}</span></a>
                <span style="padding: 10px;">{{ post.f_updated_at }}</span>
                <span style="padding: 10px;">{{ post.topic }}</span>
            </div><br>
            <div class="article-card-title">
                 <a target="_blank" href="{% url 'ys:article' id_=post.id %}">
                     <div class="article-card-title">{{ post.title }}</div>
                 </a>
            </div>
            <div class="article-card-content">
                {{ post.content|slice:":50" }}{% if post.content|length > 50 %}...{% endif %}
            </div>
            <br>
        </div>
    {% endfor %}
    </div>
</body>
</html>

play/templates/open_article.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ post.title }}</title>
    <link rel="stylesheet" href={% static 'prism.css' %}>
    <link rel="stylesheet" href="{% static 'article.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
</head>
<body>
<div class="navbar">
        <a href="{% url 'ys:home' %}">首页</a>
        <a href="{% url 'play:index' %}">首页(无需登录)</a>
        <a href="{% url 'ys:create_topic' %}" target="_blank">新建话题</a>
        <a href="{% url 'ys:write' %}" target="_blank">写文章</a>
        <div class="search-container">
            <form action="{% url 'ys:home' %}" method="get" target="_blank">
                <label>
              <input type="text" placeholder="搜索" value="" class="input1" name="search">
                    </label>
              <button class="button1" type="submit">搜索</button>
            </form>
        </div>
        <a href="{% url 'app01:login' %}">登录</a>
        <a href="{% url 'app01:user_add' %}">注册</a>
    </div>
    <hr>
    <div class="container">
            <img src="{% static post.picture %}" alt="文章封面" class="picture">
    </div>

    <div class="container">
            <h1>{{ post.title }}</h1>

            <h5>作者：<a href="{% url 'ys:user' id_=post.author.id %}" target="_blank" class="link-styled">{{ post.author }}</a></h5>
            <h5>话题：{{ post.topic }}</h5>
            <h5>发布时间：{{ post.f_created_at }}</h5>
            <h5>更新时间：{{ post.f_updated_at }}</h5>
            <a href="{% url 'ys:like_article' id_=post.id %}" class="a_button" target="_blank">点赞 {{ like_nums }}</a>
            <a href="{% url 'ys:favorite_article' id_=post.id %}" class="a_button" target="_blank">收藏 {{ favorite_nums }}</a>

        {% if flag %}
            <a href="{% url 'ys:edit' id_=post.id %}" class="a_button">编辑文章</a>
            <a href="{% url 'ys:delete_article' id_=post.id %}" class="a_button">删除文章</a>
        {% endif %}
    </div>
    <div class="container">
        <pre class="line-numbers">
            {{ post.f_content|safe }}
        </pre>

    </div>
    <div class="container">
        <div>
            <form id="comment-form" action="" method="post">{% csrf_token %}
            <!-- 提交评论的文本区域 -->
            <label class="label2" for="comment">
                <textarea  placeholder="欢迎参与讨论" id="myTextarea" oninput="autoResize()" name="comment" rows="2" cols="40" required></textarea>
            </label>
            <!-- 提交按钮 -->
            <button type="submit" class="button">提交评论</button>
            </form>
        </div>
    </div>
    <div class="container">
    <h1>评论区</h1>
        {% for comment in comments %}
        <div class="card">
        <a href="{% url 'ys:user' id_=comment.user.id %}" target="_blank" class="link-styled"><span>{{ comment.user }}</span></a>
            <p>{{ comment.content }}</p>
            <p>{{ comment.f_created_at }}</p>
        </div>
        {% endfor %}
    </div>
<script src="{% static 'prism.js' %}"></script>
<script>
    function autoResize() {
        const textarea = document.getElementById('myTextarea');
        textarea.style.height = 'auto'; // 重置高度以便重新计算
        textarea.style.height = textarea.scrollHeight + 'px'; // 设置高度为内容的实际高度
    }
</script>
</body>
</html>