app01/urls.py
from django.urls import path
from . import views
app_name = 'app01'
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    # path("user/list/", views.user_list, name="list"),
    path("user/add/", views.user_add, name="user_add"),
    # path("user/<int:id_>/delete/", views.user_delete, name="user_delete"),
    # path("user/<int:id_>/edit/", views.user_edit, name="user_edit"),
]

item/urls.py
# from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    # path('admin/', admin.site.urls),
    path("app01/", include("app01.urls")),
    path("ys/", include("ys.urls")),
    path("play/", include("play.urls")),
]

ys/urls.py
from django.urls import path
from . import views
app_name = 'ys'
urlpatterns = [
    path("home/", views.home, name="home"),
    path("user/<int:id_>/", views.user, name="user"),
    path("article/<int:id_>/", views.article, name="article"),
    path("delete/<int:id_>/article", views.delete_article, name="delete_article"),
    path("create/topic/", views.create_topic, name="create_topic"),
    path("write/", views.write, name="write"),
    path("edit/<int:id_>/", views.edit, name="edit"),
    path("like/article/<int:id_>/", views.like_article, name="like_article"),
    path("favorite/article/<int:id_>/", views.favorite_article, name="favorite_article"),

]

app01/models.py
from django.db import models

# Create your models here.


gender_choices = [
    (1, '男'),
    (0, '女'),
]
class User(models.Model):
    account = models.CharField(10, max_length=10, unique=True)
    name = models.CharField(max_length=10)
    gender = models.IntegerField(
        choices=gender_choices,
    )
    email = models.EmailField(max_length=50, null=True)
    password = models.CharField(max_length=20, default='1')

    def __str__(self):
        return self.name

ys/models.py
from django.db import models
from app01.models import User
import markdown
# Create your models here.


class Topic(models.Model):
    title = models.CharField(max_length=50, unique=True)       # 话题

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField(max_length=100)                    # 帖子标题
    content = models.TextField()                                # 帖子内容
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 帖子作者
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True)     # 话题
    created_at = models.DateTimeField(auto_now_add=True)        # 创建时间
    updated_at = models.DateTimeField(auto_now=True)             # 更新时间
    picture = models.TextField(default='', null=True)           # 图片
    @property
    def f_content(self):
        return markdown.markdown(self.content, extensions=['fenced_code'])

    @property
    def f_created_at(self):
        return self.created_at.strftime('%Y-%m-%d %H:%M:%S')

    @property
    def f_updated_at(self):
        return self.updated_at.strftime('%Y-%m-%d %H:%M:%S')


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def f_created_at(self):
        return self.created_at.strftime('%Y-%m-%d %H:%M:%S')

ys/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import models
import os
from django.db.models import Q
# from django import forms
# from .models import Video
from pathlib import Path
# Create your views here.

from datetime import datetime
from pathlib import Path
BASE_DIR = str(Path(__file__).resolve().parent.parent)
def get_safe_filename():
    # 获取当前时间
    now = datetime.now()
    # 格式化时间为字符串，包含年月日时分秒
    time_str = now.strftime("%Y-%m-%d %H:%M:%S")
    # 替换非法字符（如空格和冒号）为合法字符（如下划线）
    safe_filename = time_str.replace(" ", "_").replace(":", "-")
    return safe_filename

def create_topic(request):
    if request.method == 'GET':
        return render(request, 'create_topic.html')
    form = {
        'title': request.POST['title'],
    }
    result2 = models.Topic.objects.filter(**form)
    if result2:
        form['tip'] = '话题已存在'
        return render(request, 'create_topic.html', form)
    models.Topic.objects.create(**form)
    return redirect('ys:create_topic')


def home(request):
    search = request.GET.get('search')
    if search:
        posts = models.Post.objects.filter(Q(title__contains=search) | Q(author__name__contains=search) | Q(content__contains=search))
    else:
        posts = models.Post.objects.all()
    user = models.User.objects.get(id=request.session['info']['id'])
    return render(request, 'home.html', {'posts': posts, 'user': user})


def write(request):
    if request.method == 'GET':
        topics = models.Topic.objects.all()
        form = {'topics': topics}
        return render(request, 'write.html', form)

    form = {
        'title': request.POST['title'],
        'content': request.POST['content'],
        'picture': '#',
    }
    # 话题
    topic = models.Topic.objects.filter(id=request.POST['topic_id'])
    if topic:
        form['topic'] = topic.first()
    # 作者
    form['author'] = models.User.objects.filter(id=request.session['info']['id']).first()
    # print(form)
    obj = models.Post.objects.create(**form)
    print(obj.id)
    # 封面
    picture = request.FILES.get('picture')
    if picture:

        pic_dir = BASE_DIR+ '/static/images/' + str(obj.id)
        obj.picture = 'images/'+str(obj.id)+'.jpg'
        obj.save()
        with open(pic_dir + '.jpg', 'wb+') as f:
            for chunk in picture.chunks():
                f.write(chunk)
    return redirect('ys:article', id_=obj.id)


def edit(request, id_):
    post2 = models.Post.objects.filter(id=id_)
    if not post2:
        return HttpResponse('文章不存在')
    post = post2.first()
    if request.session['info']['id'] != post.author.id:
        return HttpResponse('无权编辑该文章')
    topics = models.Topic.objects.all()
    form = {
        'topics': topics,
        'post': post,
    }
    if request.method == 'GET':
        return render(request, 'write.html', form)
    if not request.POST['title'] or not request.POST['content']:
        return HttpResponse('文章缺失标题或内容')
    post.title = request.POST['title']
    post.content = request.POST['content']
    # 话题
    topic = models.Topic.objects.filter(id=request.POST['topic_id'])
    if topic:
        post.topic = topic.first()
    # 封面
    picture = request.FILES.get('picture')
    post.save()
    if picture:
        pic_dir = BASE_DIR+ '/static/' + post.picture
        if os.path.exists(pic_dir):
            os.remove(pic_dir)
        post.picture = "images/" + str(post.id) + get_safe_filename() + '.jpg'
        post.save()
        pic_dir = BASE_DIR+ '/static/' + post.picture
        with open(pic_dir, 'wb+') as f:
            for chunk in picture.chunks():
                f.write(chunk)
    return redirect('ys:article', id_=post.id)


def article(request, id_):
    post = models.Post.objects.filter(id=id_)
    if not post:
        return HttpResponse('文章不存在')
    post = post.first()
    if request.method == 'GET':
        comments = models.Comment.objects.filter(post=post)
        like_nums = models.Like.objects.filter(post=post).count()
        favorite_nums = models.Favorite.objects.filter(post=post).count()
        form = {
            'post': post,
            'comments': comments,
            'flag': False,
            'like_nums': like_nums,
            'favorite_nums': favorite_nums,
        }
        # print(post.author.id, request.session['info']['id'])
        if post.author.id == request.session['info']['id']:
            form['flag'] = True
        return render(request, 'article.html', form)
    comment_ = request.POST['comment']
    user_ = models.User.objects.filter(id=request.session['info']['id']).first()
    models.Comment.objects.create(user=user_, post=post, content=comment_)
    url = request.build_absolute_uri()
    return redirect(url)


def delete_article(request, id_):
    post2 = models.Post.objects.filter(id=id_)
    if not post2:
        return HttpResponse('文章不存在')
    post = post2.first()
    if request.session['info']['id'] != post.author.id:
        return HttpResponse('无权删除该文章')
    if len(post.picture)<100:
        pic_dir = BASE_DIR+ '/static/' + post.picture
        if os.path.exists(pic_dir):
            os.remove(pic_dir)
    post2.delete()
    return redirect('ys:home')


def like_article(request, id_):
    post = models.Post.objects.filter(id=id_)
    if not post:
        return HttpResponse('error')
    post = post.first()
    user = models.User.objects.filter(id=request.session['info']['id']).first()
    form = {
        'post': post,
        'user': user,
    }
    result = models.Like.objects.filter(**form)
    if result:
        result.delete()
        return HttpResponse("cancel_success")
    models.Like.objects.create(**form)
    return HttpResponse("like_success")


def favorite_article(request, id_):
    post = models.Post.objects.filter(id=id_)
    if not post:
        return HttpResponse('error')
    post = post.first()
    user = models.User.objects.filter(id=request.session['info']['id']).first()
    form = {
        'post': post,
        'user': user,
    }
    result = models.Favorite.objects.filter(**form)
    if result:
        result.delete()
        return HttpResponse("cancel_success")
    models.Favorite.objects.create(**form)
    return HttpResponse("collect_success")


def user(request, id_):
    user = models.User.objects.filter(id=id_)
    if not user:
        return HttpResponse('用户不存在')
    user = user.first()
    favorites = models.Favorite.objects.filter(user=user)

    form = {
        'user': user,
        'posts': models.Post.objects.filter(author=user),
        'favorites': favorites,
    }
    return render(request, 'user_index.html', form)

ys/templates/article.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ post.title }}</title>
    <link rel="stylesheet" href={% static 'prism.css' %}>
    <link rel="stylesheet" href="{% static 'article.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
</head>
<body>
<div class="navbar">
        <a href="{% url 'ys:home' %}">首页</a>
        <a href="{% url 'ys:create_topic' %}" target="_blank">新建话题</a>
        <a href="{% url 'ys:write' %}" target="_blank">写文章</a>
        <div class="search-container">
            <form action="{% url 'ys:home' %}" method="get" target="_blank">
                <label>
              <input type="text" placeholder="搜索" value="" class="input1" name="search">
                    </label>
              <button class="button1" type="submit">搜索</button>
            </form>
        </div>
        <a href="{% url 'app01:logout' %}">退出登录</a>
    </div>
    <hr>
    {% if post.picture %}
    	<div class="container">
            <img src="{% static post.picture %}" alt="文章封面" class="picture">
    </div>
    {% endif %}
    <div class="container">
            <h1>{{ post.title }}</h1>

            <h5>作者：<a href="{% url 'ys:user' id_=post.author.id %}" target="_blank" class="link-styled">{{ post.author }}</a></h5>
            <h5>话题：{{ post.topic }}</h5>
            <h5>发布时间：{{ post.f_created_at }}</h5>
            <h5>更新时间：{{ post.f_updated_at }}</h5>
            <button class="a_button" onclick="like({{ post.id }})">点赞{{ like_nums }}</button>
            <button class="a_button" onclick="collect({{ post.id }})">收藏{{ favorite_nums }}</button>
        {% if flag %}
            <a href="{% url 'ys:edit' id_=post.id %}" class="a_button">编辑文章</a>
            <a href="{% url 'ys:delete_article' id_=post.id %}" class="a_button">删除文章</a>
        {% endif %}
    </div>
    <div class="container">
        <pre class="line-numbers">
            {{ post.f_content|safe }}
        </pre>

    </div>
    <div class="container">
        <div>
            <form id="comment-form" action="" method="post">{% csrf_token %}
            <!-- 提交评论的文本区域 -->
            <label class="label2" for="comment">
                <textarea  placeholder="欢迎参与讨论" id="myTextarea" oninput="autoResize()" name="comment" rows="2" cols="40" required></textarea>
            </label>
            <!-- 提交按钮 -->
            <button type="submit" class="button">提交评论</button>
            </form>
        </div>
    </div>
    <div class="container">
    <h1>评论区</h1>
        {% for comment in comments %}
        <div class="card">
        <a href="{% url 'ys:user' id_=comment.user.id %}" target="_blank" class="link-styled"><span>{{ comment.user }}</span></a>
            <p>{{ comment.content }}</p>
            <p>{{ comment.f_created_at }}</p>
        </div>
        {% endfor %}
    </div>
<script src="{% static 'prism.js' %}"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/axios/1.6.7/axios.min.js"></script>
<script>
    function autoResize() {
        const textarea = document.getElementById('myTextarea');
        textarea.style.height = 'auto'; // 重置高度以便重新计算
        textarea.style.height = textarea.scrollHeight + 'px'; // 设置高度为内容的实际高度
    }
    function like(id) {
          axios({
              url: `/ys/like/article/${id}/`,
              method: 'get',
	  }).then(function (response) {
              alert(response.data);
      });
    }
    function collect(id) {
          axios({
              url: `/ys/favorite/article/${id}/`,
              method: 'get',
          }).then(function (response) {
              alert(response.data);
      });
    }
</script>
</body>
</html>

ys/templates/create_topic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>新建话题</title>
    <link rel="stylesheet" href="{% static 'create.css' %}">
</head>
<body>
    <div class="container">
        <h1>新建话题</h1>
        <form id="loginForm" method="post">{% csrf_token %}
            <div class="form-group">
                <label for="title">话题名称:</label>
                <input type="text" id="title" name="title" required value="{{ title }}">
            </div>
            <div id="message" style="color: red;">
                {{ tip }}
            </div>
            <button type="submit">提交</button>
        </form>
    </div>

</body>
</html>

ys/templates/demo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script src="{% static 'showdown.min.js' %}"></script>

<div id="markdown-content"></div>
<script>
    // 创建 showdown 实例
const converter = new showdown.Converter();

// 定义 Markdown 文本
const markdownText = '# Hello, world!\n\nThis is *Markdown* text.';

// 将 Markdown 转换为 HTML
const htmlContent = converter.makeHtml(markdownText);

// 将转换后的 HTML 插入到页面中
document.getElementById('markdown-content').innerHTML = htmlContent;
// 设置 showdown 的选项
{#converter.setOption('tables', true); // 启用表格支持#}
{#converter.setOption('tasklists', true); // 启用任务列表支持#}
// ... 其他选项
</script>
</body>
</html>

ys/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
</head>
<body>
    <div class="navbar">
        <a href="{% url 'ys:home' %}">首页</a>
        <a href="{% url 'ys:user' id_=user.id %}">我的主页</a>
        <a href="{% url 'ys:create_topic' %}" target="_blank">新建话题</a>
        <a href="{% url 'ys:write' %}" target="_blank">写文章</a>
        <div class="search-container">
            <form action="{% url 'ys:home' %}" method="get">
                <label>
              <input type="text" placeholder="搜索" value="" class="input1" name="search">
                    </label>
              <button class="button1" type="submit">搜索</button>
            </form>
        </div>
        <a href="{% url 'app01:logout' %}">退出登录</a>
    </div>
    <div class="container">
        <h1 style="text-align: center">所有帖子</h1>
    {% for post in posts %}
        <div class="article-card">
            <div class="article-card-user-info">
                <a href="{% url 'ys:user' id_=post.author.id %}" class="link-styled"><span style="padding: 10px;">{{ post.author }}</span></a>
                <span style="padding: 10px;">{{ post.f_updated_at }}</span>
                <span style="padding: 10px;">{{ post.topic }}</span>
            </div><br>
            <div class="article-card-title">
                 <a target="_blank" href="{% url 'ys:article' id_=post.id %}">
                     <div class="article-card-title">{{ post.title }}</div>
                 </a>
            </div>
            <div class="article-card-content">
                {{ post.content|slice:":50" }}{% if post.content|length > 50 %}...{% endif %}
            </div>
            <br>
        </div>
    {% endfor %}
    </div>
</body>
</html>

ys/templates/play_video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>播放视频</title>
</head>
<body>
    <video width="320" height="240" controls>
        <source src="{{ video.video_file.url }}" type="video/mp4">
        Your browser does not support the video tag.
</video>
</body>
</html>

ys/templates/upload_video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传视频</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="上传">
</form>
</body>
</html>

ys/templates/user_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ user.name }}的主页</title>
    <link rel="stylesheet" href="{% static 'user_index.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
</head>
<body>
<div class="navbar">
        <a href="{% url 'ys:home' %}">首页</a>
        <a href="{% url 'ys:create_topic' %}" target="_blank">新建话题</a>
        <a href="{% url 'ys:write' %}" target="_blank">写文章</a>
        <div class="search-container">
            <form action="{% url 'ys:home' %}" method="get">
                <label>
              <input type="text" placeholder="搜索" value="" class="input1" name="search">
                    </label>
              <button class="button1" type="submit">搜索</button>
            </form>
        </div>
        <a href="{% url 'app01:logout' %}">退出登录</a>
    </div>
    <main>
        <div class="container">
            <h5>用户名：{{ user.name }}</h5>
            <h5>性别：{{ user.get_gender_display }}</h5>
            <h5>用户账号：{{ user.account }}</h5>
        </div>
        <div class="container">
        <h2>用户所有帖子</h2>
    {% for post in posts %}
        <div class="article-card">
            <div class="article-card-user-info">
                <a href="{% url 'ys:user' id_=post.author.id %}" class="link-styled"><span style="padding: 10px;">{{ post.author }}</span></a>
                <span style="padding: 10px;">{{ post.f_updated_at }}</span>
                <span style="padding: 10px;">{{ post.topic }}</span>
            </div><br>
            <div class="article-card-title">
                 <a target="_blank" href="{% url 'ys:article' id_=post.id %}">
                     <div class="article-card-title">{{ post.title }}</div>
                 </a>
            </div>
            <div class="article-card-content">
                {{ post.content|slice:":50" }}{% if post.content|length > 50 %}...{% endif %}
            </div>
            <br>
        </div>
    {% endfor %}
    </div>
        <div class="container">
        <h2>用户收藏帖子</h2>
    {% for favorite in favorites %}
        <div class="article-card">
            <div class="article-card-user-info">
                <a href="{% url 'ys:user' id_=favorite.post.author.id %}" class="link-styled"><span style="padding: 10px;">{{ favorite.post.author }}</span></a>
                <span style="padding: 10px;">{{ favorite.post.f_updated_at }}</span>
                <span style="padding: 10px;">{{ favorite.post.topic }}</span>
            </div><br>
            <div class="article-card-title">
                 <a target="_blank" href="{% url 'ys:article' id_=favorite.post.id %}">
                     <div class="article-card-title">{{ favorite.post.title }}</div>
                 </a>
            </div>
            <div class="article-card-content">
                {{ favorite.post.content|slice:":50" }}{% if favorite.post.content|length > 50 %}...{% endif %}
            </div>
            <br>
        </div>
    {% endfor %}
    </div>
    </main>
</body>
</html>

ys/templates/write.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>写文章</title>
    <link rel="stylesheet" href={% static 'prism.css' %}>
    <link rel="stylesheet" href="{% static 'write.css' %}">
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    <div class="container">
    <h1 style="justify-content: center;text-align: center;">发布帖子</h1>

        {% csrf_token %}
        <label for="title">
            <textarea required style="height: 45px;" type="text" rows="1" id="title" name="title" placeholder="请输入标题(最多100字)">{{ post.title }}</textarea>
        </label>
        <label for="cover">
            添加封面 <input type="file" id="cover" accept="image/*" name="picture">
        </label>
        <label for="topic_id">
            选择话题 <select id="topic_id" name="topic_id">
                {% for topic in topics %}
                    <option value="{{ topic.id }}">{{ topic.title }}</option>
                {% endfor %}
            </select>
        </label>

    <img id="imagePreview" src="{% static post.picture %}" alt="预览图片">
        <input type="submit" value="发布" class="a_button">
    </div>
<div class="container2">
    <div class="editor">
            <label for="content">
            <textarea required type="text" oninput="autoResize()" rows="10" id="content" name="content" placeholder="请输入内容（支持markdown语法）">{{ post.content }}</textarea>
            </label>
        </div>

    <div class="preview">
    <pre id="preview"></pre>
    </div>
</div>
</form>
<script src="{% static 'showdown.min.js' %}"></script>
<script src="{% static 'prism.js' %}"></script>
<script>

    const fileInput = document.getElementById('cover');
    const imagePreview = document.getElementById('imagePreview');
    {% if post.picture %}
        imagePreview.style.display = 'block';
    {% endif %}
    fileInput.addEventListener('change', function() {
        const file = this.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function(e) {
                imagePreview.style.display = 'block'; // 显示预览图片
                imagePreview.src = e.target.result;
            }
            reader.readAsDataURL(file);
        } else {
            imagePreview.style.display = 'none'; // 隐藏预览图片
        }
    });
    // 创建 showdown 实例
    const converter = new showdown.Converter();

    document.getElementById('content').addEventListener('input', function() {
        let markdownText = this.value;
        const t = document.getElementById('preview');
        t.innerHTML = converter.makeHtml(markdownText);
        // 使用Prism.js对代码块进行高亮显示
        t.querySelectorAll('pre code').forEach((codeBlock) => {
            Prism.highlightElement(codeBlock);
        });
    });
    function autoResize() {
        const textarea = document.getElementById('content');
        textarea.style.height = 'auto'; // 重置高度以便重新计算
        textarea.style.height = textarea.scrollHeight + 'px'; // 设置高度为内容的实际高度
    }
</script>
</body>
</html>